### PR TITLE
fix the issue since ubuntu 18

### LINKED ISSUE #4: does not compile on ubuntu since version 18 due to libpng
in the latest version of ubuntu libpng has been updated. It now requires to add the argument -lpng at the end of the command `gcc`. I have already made a pull request here: https://github.com/raphnet/gbcam2png/pull/3 . Fell free to merge.

### PR DESCRIPTION
**Pull request by gogo2464**
Fixes [#4](https://github.com/raphnet/gbcam2png/issues/4).

Ready to merge.

### CODE REVIEW

**Comment by raphnet** [comment]
`libpng-config --libs` should be providing the -lpng argument. Why is this needed?

**Comment by gogo2464** [comment]
@raphnet Simply because it does not compile anymore. I openned and issue here: https://github.com/raphnet/gbcam2png/issues/4 

Just to let you know, now the -lpng should be placed at the end. You can check out on ubuntu 20 it will not work anymore if you do not apply my changes.


It works on my machine. :)

**Comment by raphnet** [comment]
What is the output of libpng-config --libs on your machine?

**Comment by gogo2464** [comment]
-lpng16 of course. As you can see it is 16. Not 12.

**Comment by gogo2464** [comment]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by raphnet** [comment]
The idea has always been that the required libraries should be provided by libpng-config, or pkg-config. I'm sure adding -lpng works fine, but I would like to understand why suddenly the libpng-config method no longer works.

**Comment by gogo2464** [comment]
Before that I made the change, When I did `make` I got:

`make`

```
gcc -Wall -O1 `libpng-config --cflags`   -c -o main.o main.c
gcc -Wall -O1 `libpng-config --cflags`   -c -o gbphoto.o gbphoto.c
gcc -Wall -O1 `libpng-config --cflags`   -c -o pngwriter.o pngwriter.c
gcc `libpng-config --libs` -o gbcam2png main.o gbphoto.o pngwriter.o
/usr/bin/ld : pngwriter.o : dans la fonction « gbphoto_writepng » :
pngwriter.c:(.text+0x162) : référence indéfinie vers « png_create_write_struct »
/usr/bin/ld : pngwriter.c:(.text+0x177) : référence indéfinie vers « png_create_info_struct »
/usr/bin/ld : pngwriter.c:(.text+0x1af) : référence indéfinie vers « png_destroy_write_struct »
/usr/bin/ld : pngwriter.c:(.text+0x227) : référence indéfinie vers « png_destroy_write_struct »
/usr/bin/ld : pngwriter.c:(.text+0x24f) : référence indéfinie vers « png_init_io »
/usr/bin/ld : pngwriter.c:(.text+0x28e) : référence indéfinie vers « png_set_IHDR »
/usr/bin/ld : pngwriter.c:(.text+0x2a8) : référence indéfinie vers « png_set_PLTE »
/usr/bin/ld : pngwriter.c:(.text+0x2b5) : référence indéfinie vers « png_write_info »
/usr/bin/ld : pngwriter.c:(.text+0x346) : référence indéfinie vers « png_write_row »
/usr/bin/ld : pngwriter.c:(.text+0x3a4) : référence indéfinie vers « png_write_end »
/usr/bin/ld : pngwriter.c:(.text+0x3b1) : référence indéfinie vers « png_destroy_write_struct »
collect2: error: ld returned 1 exit status
make: *** [Makefile:10 : gbcam2png] Erreur 1
```

**Comment by gogo2464** [comment]
> The idea has always been that the required libraries should be provided by libpng-config, or pkg-config. I'm sure adding -lpng works fine, but I would like to understand why suddenly the libpng-config method no longer works.

I found a short comment by a libpng developper on stackoverflow. I do not find it anymore.

**Comment by raphnet** [comment]
Thanks! It still compiles on Debian here.. Hold on, I'll do some testing in a Ubuntu VM now. I'm not saying adding -lpng is wrong, it's just that the libpng-config should be more portable in theory and I'd like to understand what's going on with that no longer working.

**Comment by gogo2464** [comment]
> Thanks! It still compiles on Debian here.. Hold on, I'll do some testing in a Ubuntu VM now. I'm not saying adding -lpng is wrong, it's just that the libpng-config should be more portable in theory and I'd like to understand what's going on with that no longer working.

Then I suggest to try on debian, if it works on debian with libpng 12 with my code, we will accept my Pull Request. If it does not I will make a if else in Makefile where I will use old version for libpng 12 and the new version of makefile for libpng 16.

**Comment by gogo2464** [comment]
This another post might explain why: https://stackoverflow.com/questions/36674667/png-h-file-not-found-linux/56860860#56860860

**Comment by raphnet** [comment]
Ok, I reproduced the problem under Ubuntu, and it was simply due to the order of the arguments when linking. $(LDFLAGS) should have been last. Why you added -lpng at the end, that fixed it.

**Comment by gogo2464** [comment]
I just found my comment again about the order. It does not really explain why. See https://askubuntu.com/questions/916916/libpng-dev-is-installed-program-doesnt-link#comment1445588_916916

**Comment by raphnet** [comment]
Well one of the comments in the thread you provided a link to mentions:

>  It makes a difference where in the command you write this option; the linker searches and processes libraries and object files in the order they are specified. Thus, foo.o -lz bar.o searches library z after file foo.o but before bar.o. If bar.o refers to functions in z, those functions may not be loaded.
> https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html

I have been bitten by this when statically linking in the past, so it makes sense. It is the first time I see this when dynamically linking however, but gcc/ld evolves... I am satisfied with this explanation.

This explains why adding -lpng at the end worked. I pushed an equivalent fix that moves the $(LDFLAGS) variable at the end, since I want the "-lpng" part to come from the output of libpng-config instead of hardcoded.

Thanks for bringing this to my attention! I think we can close the pull request?

**Comment by gogo2464** [comment]
Yes you can close. I just would like to see if I can not pul the change on my PR and then push to the history to get a better git history.

**Comment by gogo2464** [comment]
Ok it will not be really better. I just would like to show that I contributed.

**Comment by gogo2464** [comment]
Yes but my commit is empty. You have already commited and I solve conflict to allow all your change. can you just undo you changes and let me rebase?

**Comment by gogo2464** [comment]
Oops I have revert. I believed it was going to reset your history. I think you are the only person allowed to do that. Please just reset and then merge this PR https://github.com/raphnet/gbcam2png/pull/5 Sorry for the inconvenience.

**Pull request merged**
